### ISSUE TITLE
Brainstorm para indicações de ideias em projetos de software

### ISSUE THREAD

**Issue by radamesp7** [radamesp7/AbexII_G11_2024#1]
O brainstorming se aplica a disciplina de aprendizado baseado em experiências, onde os alunos em grupos indicam o que pode ser uma ideia de problema que possa ser solucionado com o desenvolvimento de um aplicativo de software e que tem uma finalidade prática. O brainstoriming deve gerar ideias entre os membros do grupo e precisa que se use como base o github para que possam trabalhar como grupo de trabalho e registrar as ideias conforme forem gerando as mesmas.

 Lista de Ideias:

**Comment by JoaoBezutti** [comment]
aplicativo para facilitar a mobilidade urbana com transporte público

**Comment by lucasVII** [comment]
Reclame Aqui (por exemplo: descobrir qual microondas funciona na Uno)

**Comment by lucasVII** [comment]
planer diário customizável com 'pq é importante', imagens e tals

**Comment by lucasVII** [comment]
app nutrição, suplementos, o que combina, o que não combina, o que prejudica sono, o que deve ser ingerido com alimento, o que deve ser ingerido em jejum

**Comment by lucasVII** [comment]
curso para concursos de nível médio que se possa fazer lições de 5 minutos no ônibus no trajeto trabalho - casa

**Comment by JoaoBezutti** [comment]
aplicativo de geolocalização para saber onde tem vaga de estacionamento na proximidade

**Comment by lucasVII** [comment]
> aplicativo de geolocalização para saber onde tem vaga de estacionamento na proximidade

com níveis de dificuldade

**Comment by lucasVII** [comment]
beecrowd, mas com step by step solution

**Comment by pavanpauline** [comment]
agendamento de consulta online para o sus

**Comment by pavanpauline** [comment]
app que auxilia na economia de energia (mede o gasto e da dicas para economia) - em casas inteligentes

**Comment by pavanpauline** [comment]
cozinha inteligente - app onde a pessoa informa quais ingredientes ela possui em casa e ele sugere quais receitas ela pode fazer com base nos ingredientes

**Comment by JoaoBezutti** [comment]
app para ajudar na contagem diária de ingestão e queima de calorias

**Comment by lucasVII** [comment]
sempre sonhei com isso Pauline

**Comment by lucasVII** [comment]
Professor, as ideias que eu coloquei durante a aula não constaram aqui.
Alguém saberia pq?
